import { Territory, Club, War } from "@/types/war";
import { COLORS } from "./colors";

export const CLUBS: Club[] = [
  { id: "alpha", name: "ALPHA", shortName: "A", color: COLORS.club.alpha, logo: "🛡️" },
  { id: "omega", name: "OMEGA", shortName: "Ω", color: COLORS.club.omega, logo: "⚔️" },
  { id: "sigma", name: "SIGMA", shortName: "Σ", color: COLORS.club.sigma, logo: "⚡" },
  { id: "gamma", name: "GAMMA", shortName: "Γ", color: COLORS.club.gamma, logo: "🌿" },
];

export const TERRITORIES: Territory[] = [
  {
    id: "france",
    name: "FRANCE",
    paths: "M 280 420 L 320 410 L 340 440 L 330 470 L 300 480 L 270 460 Z",
    position: { x: 305, y: 445 },
    color: COLORS.territory.france.base,
    glowColor: COLORS.territory.france.glow,
    borderColor: COLORS.territory.france.border,
    state: "critical",
    club: CLUBS[0],
  },
  {
    id: "spain",
    name: "SPAIN",
    paths: "M 200 480 L 260 470 L 270 510 L 240 540 L 200 530 Z",
    position: { x: 235, y: 505 },
    color: COLORS.territory.spain.base,
    glowColor: COLORS.territory.spain.glow,
    borderColor: COLORS.territory.spain.border,
    state: "conquered",
    club: CLUBS[2],
  },
  {
    id: "poland",
    name: "POLAND",
    paths: "M 480 350 L 530 340 L 550 370 L 540 400 L 490 410 Z",
    position: { x: 515, y: 370 },
    color: COLORS.territory.poland.base,
    glowColor: COLORS.territory.poland.glow,
    borderColor: COLORS.territory.poland.border,
    state: "high",
    club: CLUBS[3],
  },
  {
    id: "italy",
    name: "ITALY",
    paths: "M 380 460 L 420 450 L 430 490 L 415 520 L 380 510 Z",
    position: { x: 405, y: 485 },
    color: COLORS.territory.italy.base,
    glowColor: COLORS.territory.italy.glow,
    borderColor: COLORS.territory.italy.border,
    state: "idle",
    club: CLUBS[0],
  },
  {
    id: "uk",
    name: "UK",
    paths: "M 250 340 L 290 330 L 300 360 L 280 380 L 250 370 Z",
    position: { x: 275, y: 355 },
    color: COLORS.territory.inactive.base,
    glowColor: COLORS.territory.inactive.glow,
    borderColor: COLORS.territory.inactive.border,
    state: "idle",
    club: CLUBS[0],
  },
  {
    id: "germany",
    name: "GERMANY",
    paths: "M 370 370 L 420 360 L 440 390 L 430 420 L 380 430 Z",
    position: { x: 405, y: 390 },
    color: COLORS.territory.inactive.base,
    glowColor: COLORS.territory.inactive.glow,
    borderColor: COLORS.territory.inactive.border,
    state: "idle",
    club: CLUBS[1],
  },
  {
    id: "sweden",
    name: "SWEDEN",
    paths: "M 420 260 L 470 250 L 480 290 L 460 310 L 420 300 Z",
    position: { x: 450, y: 280 },
    color: COLORS.territory.inactive.base,
    glowColor: COLORS.territory.inactive.glow,
    borderColor: COLORS.territory.inactive.border,
    state: "idle",
    club: CLUBS[1],
  },
  {
    id: "norway",
    name: "NORWAY",
    paths: "M 360 220 L 410 210 L 420 250 L 400 270 L 360 260 Z",
    position: { x: 390, y: 240 },
    color: COLORS.territory.inactive.base,
    glowColor: COLORS.territory.inactive.glow,
    borderColor: COLORS.territory.inactive.border,
    state: "idle",
    club: CLUBS[2],
  },
];

export const INITIAL_WARS: War[] = [
  {
    id: "war-france",
    territoryId: "france",
    territoryName: "FRANCE",
    attacker: CLUBS[1],
    defender: CLUBS[0],
    progress: 65,
    priority: "critical",
    timeRemaining: "02:34",
  },
  {
    id: "war-poland",
    territoryId: "poland",
    territoryName: "POLAND",
    attacker: CLUBS[2],
    defender: CLUBS[3],
    progress: 42,
    priority: "high",
    timeRemaining: "05:12",
  },
  {
    id: "war-poland-2",
    territoryId: "poland",
    territoryName: "POLAND",
    attacker: CLUBS[1],
    defender: CLUBS[3],
    progress: 28,
    priority: "medium",
    timeRemaining: "08:45",
  },
];
