project_id = "bbxvpirknqzvjhezrqpo"

[functions.pandascore-matches]
verify_jwt = false

[functions.send-support-status]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.daily-pick-reminder]
verify_jwt = false

[functions.resolve-picks]
verify_jwt = false
