import { Gift, Shield, Swords, TrendingUp } from "lucide-react";

import type { LiveWar } from "@/hooks/useLiveWars";

import type { FeedItem, ObjectiveItem } from "./types";

export const fallbackFronts: LiveWar[] = [
  {
    territory_id: "north-realm",
    territory_name: "North Realm",
    lat: 52,
    lng: 18,
    gold_income: null,
    energy_income: null,
    upkeep_cost: null,
    capture_progress: 78,
    club_id: null,
    club_name: "Team Alpha",
    club_color: "#22d3ee",
    alliance_id: null,
    alliance_name: null,
    war_id: "fallback-war-1",
    status: "safe zone",
    total_xp: 1560,
  },
  {
    territory_id: "central-zone",
    territory_name: "Central Zone",
    lat: 48,
    lng: 8,
    gold_income: null,
    energy_income: null,
    upkeep_cost: null,
    capture_progress: 85,
    club_id: null,
    club_name: "Club Omega",
    club_color: "#f97316",
    alliance_id: null,
    alliance_name: null,
    war_id: "fallback-war-2",
    status: "pressure rising",
    total_xp: 2240,
  },
  {
    territory_id: "east-reach",
    territory_name: "East Reach",
    lat: 51,
    lng: 31,
    gold_income: null,
    energy_income: null,
    upkeep_cost: null,
    capture_progress: 66,
    club_id: null,
    club_name: "Rally needed",
    club_color: "#f59e0b",
    alliance_id: null,
    alliance_name: null,
    war_id: "fallback-war-3",
    status: "rally needed",
    total_xp: 980,
  },
  {
    territory_id: "south-sector",
    territory_name: "South Sector",
    lat: 42,
    lng: 11,
    gold_income: null,
    energy_income: null,
    upkeep_cost: null,
    capture_progress: 52,
    club_id: null,
    club_name: "Rival Spire",
    club_color: "#8b5cf6",
    alliance_id: null,
    alliance_name: null,
    war_id: "fallback-war-4",
    status: "contested",
    total_xp: 720,
  },
];

export const feedItems: FeedItem[] = [
  { icon: Shield, label: "Team Alpha rallied 12 members", time: "2 mins ago", tone: "cyan" },
  { icon: TrendingUp, label: "North Realm pressure increased", time: "4 mins ago", tone: "orange" },
  { icon: Swords, label: "Club Omega defended Central Zone", time: "7 mins ago", tone: "violet" },
  { icon: Gift, label: "New reward tier unlocked", time: "10 mins ago", tone: "emerald" },
];

export const objectives: ObjectiveItem[] = [
  {
    cta: "View Map",
    progress: "65%",
    rewardLabel: "Reward:",
    rewardValue: "Rare Emblem",
    state: "In Progress",
    title: "Capture First Territory",
    tone: "cyan",
  },
  {
    cta: "Reinforce",
    progress: "90%",
    rewardLabel: "Reward:",
    rewardValue: "+500 Prestige",
    state: "Almost There",
    title: "Defend Current Zone",
    tone: "orange",
  },
  {
    cta: "Invite",
    progress: "3/5",
    rewardLabel: "Reward:",
    rewardValue: "Squad Bonus",
    state: "Active",
    title: "Rally 5 Members",
    tone: "cyan",
  },
  {
    cta: "Claim Reward",
    progress: "100%",
    rewardLabel: "Reward:",
    rewardValue: "Voice Boost Badge",
    state: "Completed",
    title: "Complete Daily Live Call",
    tone: "emerald",
  },
];
